ChatWithMe/urls.py
from django.contrib import admin
from django.urls import path, include

from ChatWithMe import views

app_name = 'ChatWithMe'
urlpatterns = [
    path("", views.main, name='main'),
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls")),
    path('auth/', include('authentication.urls')),
]

authentication/urls.py
from django.urls import path

from . import views

app_name = "authentication"
urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:room_id>/", views.room, name="room"),
]

authentication/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model

# room 
class Room(models.Model):
    id = models.AutoField(primary_key=True)
    room_name = models.TextField(max_length=50)
    host = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='room_admin')
    room_mempers = models.ManyToManyField(get_user_model())
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.room_name


# messages table
class Message(models.Model):
    sender = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="sent_messages"
    )

    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10)  # this to store the message status

    def __str__(self):
        return f"{self.sender} send \"{self.content}\" to {self.room.room_name} room"

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

ChatWithMe/views.py
from django.shortcuts import render


def main(request):
    context = {
        "page_name": "Chat With Me",
    }
    return render(request, "main.html", context)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from .forms import NewUserForm


def register_user(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            request.session["username"] = user.get_username()
            request.session.save()

            return redirect("chat:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")

    form = NewUserForm()
    context = {
        "register_form": form,
        "page_name": "Register User",
    }
    return render(
        request,
        "authentication/register_user.html",
        context,
    )


def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)

                request.session["username"] = user.get_username()
                request.session.save()

                return redirect("chat:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")

    form = AuthenticationForm()
    context = {
        "login_form": form,
        "page_name": "Login User",
    }
    return render(
        request,
        "authentication/login_user.html",
        context,
    )


@login_required(login_url="authentication:login_user")
def logout_user(request):
    logout(request)
    return redirect("main")

chat/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.http import JsonResponse

import json

from .models import Room, Message


@login_required(login_url="authentication:login_user")
def index(request):
    if request.method == "POST":
        room_name = request.POST.get("room_name")
        if room_name is not None:
            username = request.session.get("username")
            current_user = get_user_model().objects.get(username=username)

            rooms = Room.objects.filter(room_name__icontains=room_name).order_by(
                "-timestamp"
            )

            # return rooms that i memper in only
            my_rooms = []
            for room in rooms:
                if current_user in room.room_mempers.all():
                    my_rooms.append(room)

        context = {
            "page_name": "chat",
            "rooms": my_rooms,
        }
        return render(request, "chat/index.html", context)

    context = {
        "page_name": "chat",
    }
    return render(request, "chat/index.html", context)


@login_required(login_url="authentication:login_user")
def room(request, room_id):
    room = Room.objects.get(id=room_id)

    username = request.session.get("username")
    current_user = get_user_model().objects.get(username=username)

    context = {
        "page_name": room.room_name,
        "room": room,
    }

    if current_user in room.room_mempers.all():
        request.session["room_id"] = room_id
        request.session.save()

        # get room messages
        # and send them to frontend
        # to display it
        current_room = Room.objects.get(id=room_id)
        messages_for_current_room = Message.objects.filter(room=room)

        context["room_messages"] = messages_for_current_room

        return render(request, "chat/room.html", context)
    else:
        messages.error(request, "You are unauthorized to access this room.")
        return render(request, "chat/room.html", context)

authentication/templates/authentication/login_user.html
{% extends 'main.html' %} {% block content %}
{% load crispy_forms_tags %}
<div class="container">
  <div class="background">
    <div class="shape"></div>
    <div class="shape"></div>
  </div>

  <form method="POST">
    {% csrf_token %}
    <h3>Login</h3>

    {{ login_form|crispy }}

    <input type="submit" value="Login" class="submit" />

    <a href="{% url 'authentication:register_user'%}" class="link"
      >I don't have account.</a
    >
  </form>
</div>
{% endblock content %}

authentication/templates/authentication/register_user.html
{% extends 'main.html' %} {% block content %}
{% load crispy_forms_tags %}
<div class="container">
  <div class="background">
    <div class="shape"></div>
    <div class="shape"></div>
  </div>
  <form method="POST">
    {% csrf_token %}
    <h3>Register</h3>

    {{ register_form|crispy }}

    <input type="submit" value="Register" class="submit" />

    <a href="{% url 'authentication:login_user'%}" class="link"
      >I have account.</a
    >
  </form>
</div>
{% endblock content %}

chat/templates/chat/index.html
{% extends "main.html" %} {% block content %}
<form method="POST" action=''>
  <p>What chat room would you like to enter?</p>
  {% csrf_token %}
  <input
    id="room-name-input"
    type="text"
    name="room_name"
    placeholder="room name"
  /><br />
  <input id="room-name-submit" type="submit" value="Enter" />
</form>

<ul>
  {% for room in rooms %}
  <li><a href="{{room.id}}">{{room}}</a></li>
  {% endfor %}
</ul>

<script>
  document.querySelector("#room-name-input").focus();
  document.querySelector("#room-name-input").onkeyup = function (e) {
    if (e.key === "Enter") {
      //enter, return
      document.querySelector("#room-name-submit").click();
    }
  };
</script>
{% endblock content %}

chat/templates/chat/room.html
{% extends "main.html" %} {% block content %}

<h1>{{room.room_name}} by {{room.host.username}}</h1>

{% if messages %}
<input type="button" value="go back" onclick="history.back();" />
{% else %}
<textarea id="chat-log" cols="75" rows="15"></textarea><br />
<input id="chat-message-input" type="text" /><br />
<input id="chat-message-submit" type="button" value="Send" />
{{ room.room_name|json_script:'room-name'}}
{{ room.host.username|json_script:'host' }}

<script>
  chat_box = document.querySelector('#chat-log')
  {% for message in room_messages %}
    chat_box.value += '\n::' + "{{message.sender}}";
    chat_box.value += ' > ' + "{{message.timestamp}}";
    chat_box.value += '\n' + "{{message.content}}";
  {% endfor %}
  chat_box.scrollTop = chat_box.scrollHeight;
</script>

<script>
  const roomName = JSON.parse(document.getElementById("room-name").textContent);

  const chatSoket = new WebSocket(
    "ws://" + window.location.host + "/ws/chat/" + roomName + "/"
  );

  chatSoket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    document.querySelector("#chat-log").value +=
      "\n::" + data.sender + ' > ' + data.message_time + "\n" + data.message;
    
    chat_box.scrollTop = chat_box.scrollHeight;
  };

  chatSoket.onclose = function (e) {
    console.error("Chat socket closed unexpectedly");
  };

  document.querySelector("#chat-message-input").focus();
  document.querySelector("#chat-message-input").onkeyup = function (e) {
    if (e.key === "Enter") {
      //enter, return
      document.querySelector("#chat-message-submit").click();
    }
  };

  document.querySelector("#chat-message-submit").onclick = function (e) {
    const messageInputDom = document.querySelector("#chat-message-input");
    const message = messageInputDom.value;
    chatSoket.send(
      JSON.stringify({
        message: message,
        sender: host,
      })
    );

    messageInputDom.value = "";
  };
</script>
{% endif %} {% endblock content %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'authentication/style.css' %}" />
    <link rel="stylesheet" href="{% static 'authentication/auth.css' %}" />
    <title>{{page_name}}</title>
  </head>
  <body>
    {% if messages %}
    <ul class="error_messages">
      {% for message in messages %}
      <li>{{ message}}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <div class="header">
      {% comment %} app logo {% endcomment %}
      <a href="{% url 'main'%}" class="logo">Chat with me</a>
      {% comment %} end app logo {% endcomment %} {% comment %} room search {%
      endcomment %} {% comment %} end room search {% endcomment %} {% comment %}
      login and logout buttons {% endcomment %} 
      
      {% if request.user.is_authenticated%}
      <a href="{% url 'authentication:logout_user'%}" class="login_bt"
        >Logout</a
      >
      {% elif page_name != 'Login User' and page_name != 'Register User' %}
      <a href="{% url 'authentication:login_user'%}" class="login_bt">Login</a>
      {% endif %} {% comment %} end login and logout buttons {% endcomment %}
    </div>

    {% block content %} {% endblock content %}
  </body>
</html>